New Instance 2015

diff --git a/.travis.yml b/.travis.yml
--- a/.travis.yml
+++ b/.travis.yml
@@ -1,9 +1,12 @@
 # Travis CI configuration file for running tests
 language: python
+branches:
+  only:
+    - master
 python:
   - "2.7"
 install:
-  - "sudo apt-get install -y npm python-demjson"
+  - "sudo apt-get install -y nodejs python-demjson"
   - "pip install --allow-all-external -r requirements.txt"
   - "pip install --allow-all-external demjson"
 script:
@@ -24,9 +27,36 @@ script:
       fi
     done
   - |
-    plays="aws bastion certs commoncluster common demo devpi discern edx_ansible edxapp elasticsearch forum ora rabbitmq worker xqueue xserver"
-    set -e
-    cd playbooks/edx-east
-    for play in $plays; do
-      ansible-playbook -i localhost, --syntax-check ${play}.yml
+    pushd playbooks
+    for j2 in $(git diff --name-only refs/heads/master..$(git rev-parse --abbrev-ref HEAD) |grep -E '.+\.j2$|.+\.yml'); do
+      python ../tests/jinja_check.py ../$j2
+      if [[ $? -ne 0 ]]; then
+          echo "Jinja parsing error on $j2"
+          exit 1
+      fi
     done
+    popd
+  - |
+    set -e
+    ROOT_DIR=$PWD
+    cd playbooks/edx-east
+    ROLE_DIRS=$(/bin/ls -d roles/*)
+    cat <<EOF >travis-test.yml
+    - name: Play to test all roles
+      hosts: all
+      roles:
+    EOF
+    for role_dir in $ROLE_DIRS; do
+        echo "    - $(basename $role_dir)" >> travis-test.yml
+    done
+
+    ansible-playbook -i localhost, --syntax-check travis-test.yml
+
+    output_dir="$PWD/test_output/env-dep"
+    mkdir -p $output_dir
+    ansible-playbook -i localhost, -c local --tags edxapp_cfg edxapp.yml -e edxapp_user=`whoami` -e edxapp_app_dir=$output_dir -e edxapp_code_dir=$output_dir -e EDXAPP_CFG_DIR=$output_dir
+
+    root_dir=$output_dir
+    environment_deployments="."
+    source $ROOT_DIR/tests/validate_templates.sh
+
